-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 17:00:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hogardb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hogardb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hogardb` DEFAULT CHARACTER SET utf8 ;
USE `hogardb` ;

-- -----------------------------------------------------
-- Table `hogardb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`Persona` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `tipodocumento` VARCHAR(15) NOT NULL,
  `documento` VARCHAR(30) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`adopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`adopcion` (
  `idadopcion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `observacion` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idadopcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`raza` (
  `idraza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idraza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`mascota` (
  `idmascota` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `edad` VARCHAR(3) NOT NULL,
  `tamaño` VARCHAR(10) NOT NULL,
  `genero` VARCHAR(10) NOT NULL,
  `ubicacion` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `especie` VARCHAR(10) NOT NULL,
  `raza_idraza` INT NOT NULL,
  PRIMARY KEY (`idmascota`, `raza_idraza`),
  INDEX `fk_mascota_raza1_idx` (`raza_idraza` ASC) ,
  CONSTRAINT `fk_mascota_raza1`
    FOREIGN KEY (`raza_idraza`)
    REFERENCES `hogardb`.`raza` (`idraza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`foto` (
  `idfoto` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`veterinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`veterinaria` (
  `idveterinaria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `funcionario` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idveterinaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`atencionmedica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`atencionmedica` (
  `idatencionmedica` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `diagnostico` VARCHAR(100) NOT NULL,
  `tratamiento` VARCHAR(100) NOT NULL,
  `veterinaria_idveterinaria` INT NOT NULL,
  PRIMARY KEY (`idatencionmedica`, `veterinaria_idveterinaria`),
  INDEX `fk_atencionmedica_veterinaria1_idx` (`veterinaria_idveterinaria` ASC) ,
  CONSTRAINT `fk_atencionmedica_veterinaria1`
    FOREIGN KEY (`veterinaria_idveterinaria`)
    REFERENCES `hogardb`.`veterinaria` (`idveterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`recurso` (
  `idrecurso` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NULL,
  `donacion` INT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idrecurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`serviciomedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`serviciomedico` (
  `idserviciomedico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `atencionmedica_idatencionmedica` INT NOT NULL,
  PRIMARY KEY (`idserviciomedico`, `atencionmedica_idatencionmedica`),
  INDEX `fk_serviciomedico_atencionmedica1_idx` (`atencionmedica_idatencionmedica` ASC) ,
  CONSTRAINT `fk_serviciomedico_atencionmedica1`
    FOREIGN KEY (`atencionmedica_idatencionmedica`)
    REFERENCES `hogardb`.`atencionmedica` (`idatencionmedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`tipogasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`tipogasto` (
  `idtipogasto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipogasto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`gasto` (
  `idgasto` INT NOT NULL AUTO_INCREMENT,
  `valor` INT NOT NULL,
  `fechaini` DATE NOT NULL,
  `fechafin` DATE NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `documento` VARCHAR(45) NULL,
  `tipogasto_idtipogasto` INT NOT NULL,
  PRIMARY KEY (`idgasto`, `tipogasto_idtipogasto`),
  INDEX `fk_gasto_tipogasto1_idx` (`tipogasto_idtipogasto` ASC) ,
  CONSTRAINT `fk_gasto_tipogasto1`
    FOREIGN KEY (`tipogasto_idtipogasto`)
    REFERENCES `hogardb`.`tipogasto` (`idtipogasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`refugio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`refugio` (
  `idrefugio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`idrefugio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hogardb`.`cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`cuestionario` (
  `idcuestionario` INT NOT NULL AUTO_INCREMENT,
  `preg1` DATE NOT NULL,
  `preg2` VARCHAR(20) NOT NULL,
  `preg3` VARCHAR(10) NOT NULL,
  `preg4` VARCHAR(3) NOT NULL,
  `preg5` VARCHAR(3) NOT NULL,
  `preg6` VARCHAR(15) NOT NULL,
  `preg7` VARCHAR(15) NOT NULL,
  `preg8` VARCHAR(10) NOT NULL,
  `preg9` VARCHAR(10) NOT NULL,
  `preg10` VARCHAR(30) NOT NULL,
  `preg11` VARCHAR(15) NOT NULL,
  `preg12` VARCHAR(20) NOT NULL,
  `preg13` VARCHAR(30) NOT NULL,
  `preg14` VARCHAR(20) NOT NULL,
  `preg15` VARCHAR(40) NOT NULL,
  `preg16` VARCHAR(20) NOT NULL,
  `preg17` VARCHAR(20) NOT NULL,
  `preg18` VARCHAR(30) NOT NULL,
  `preg19` VARCHAR(40) NOT NULL,
  `preg20` VARCHAR(40) NOT NULL,
  `preg21` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcuestionario`))
ENGINE = InnoDB;

USE `hogardb` ;

-- -----------------------------------------------------
-- Placeholder table for view `hogardb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hogardb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hogardb`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `hogardb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hogardb`.`view1`;
USE `hogardb`;


-- -----------------------------------------------------
-- View `hogardb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hogardb`.`view2`;
USE `hogardb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
